// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhysicalTherapy.Models;

namespace PhysicalTherapy.Migrations
{
    [DbContext(typeof(PhysicalTherapyContext))]
    [Migration("20190115050027_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhysicalTherapy.Models.Administrator", b =>
                {
                    b.Property<int>("AdministratorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountType");

                    b.Property<string>("Bio");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("AdministratorId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.Credential", b =>
                {
                    b.Property<int>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountType");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("CredentialId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ExerciseId");

                    b.ToTable("Excercises");

                    b.HasData(
                        new { ExerciseId = 1, Area = "Knee", Description = "", Name = "Quad Sets" },
                        new { ExerciseId = 2, Area = "Knee", Description = "", Name = "Knee Slides with Towel" },
                        new { ExerciseId = 3, Area = "Knee", Description = "", Name = "Prone Knee Hang" },
                        new { ExerciseId = 4, Area = "Knee", Description = "", Name = "Step Knee Flexion" },
                        new { ExerciseId = 5, Area = "Knee", Description = "", Name = "Calf Stretch" },
                        new { ExerciseId = 6, Area = "Knee", Description = "", Name = "Hamstring Stretch" },
                        new { ExerciseId = 7, Area = "Knee", Description = "", Name = "Ice to Knee with Elevation" }
                    );
                });

            modelBuilder.Entity("PhysicalTherapy.Models.MessageLog", b =>
                {
                    b.Property<int>("MessageLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InsertDate");

                    b.Property<string>("Message");

                    b.Property<int?>("PatientId");

                    b.Property<int?>("RoutineId");

                    b.Property<int?>("TherapistId");

                    b.HasKey("MessageLogId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoutineId");

                    b.HasIndex("TherapistId");

                    b.ToTable("MessageLogs");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountType");

                    b.Property<string>("Bio");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int?>("TherapistId");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("PatientId");

                    b.HasIndex("TherapistId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.PostRoutineSurvey", b =>
                {
                    b.Property<int>("PostRoutineSurveyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Completed");

                    b.Property<int>("LevelOfDifficulty");

                    b.Property<int>("LevelOfPain");

                    b.Property<int>("LevelOfTiredness");

                    b.Property<string>("Note");

                    b.HasKey("PostRoutineSurveyId");

                    b.ToTable("PostRoutineSurveys");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.Routine", b =>
                {
                    b.Property<int>("RoutineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsComplete");

                    b.Property<int>("PatientId");

                    b.Property<int?>("PostRoutineSurveyId");

                    b.Property<bool>("isNew");

                    b.HasKey("RoutineId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PostRoutineSurveyId")
                        .IsUnique()
                        .HasFilter("[PostRoutineSurveyId] IS NOT NULL");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.RoutineExercise", b =>
                {
                    b.Property<int>("RoutineExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExerciseId");

                    b.Property<int?>("FrequencyPerDay");

                    b.Property<decimal?>("HoldLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes");

                    b.Property<int?>("Rep");

                    b.Property<int>("RoutineId");

                    b.Property<int?>("Sets");

                    b.HasKey("RoutineExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineExercises");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.Therapist", b =>
                {
                    b.Property<int>("TherapistId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountType");

                    b.Property<string>("Bio");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("TherapistId");

                    b.ToTable("Therapists");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.MessageLog", b =>
                {
                    b.HasOne("PhysicalTherapy.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.HasOne("PhysicalTherapy.Models.Routine", "Routine")
                        .WithMany("ListOfMessageLogs")
                        .HasForeignKey("RoutineId");

                    b.HasOne("PhysicalTherapy.Models.Therapist", "Therapist")
                        .WithMany()
                        .HasForeignKey("TherapistId");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.Patient", b =>
                {
                    b.HasOne("PhysicalTherapy.Models.Therapist", "Therapist")
                        .WithMany("ListOfPatients")
                        .HasForeignKey("TherapistId");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.Routine", b =>
                {
                    b.HasOne("PhysicalTherapy.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhysicalTherapy.Models.PostRoutineSurvey", "PostRoutineSurvey")
                        .WithOne()
                        .HasForeignKey("PhysicalTherapy.Models.Routine", "PostRoutineSurveyId");
                });

            modelBuilder.Entity("PhysicalTherapy.Models.RoutineExercise", b =>
                {
                    b.HasOne("PhysicalTherapy.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhysicalTherapy.Models.Routine", "Routine")
                        .WithMany("RoutineExercises")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
